"""add document relation

Revision ID: 385b77dc0cfb
Revises: 95a91eabc6ff
Create Date: 2025-01-29 18:22:23.954453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385b77dc0cfb'
down_revision: Union[str, None] = '95a91eabc6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_parcel_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'parcel_id')
    op.drop_constraint('parcels_document_fkey', 'parcels', type_='foreignkey')
    op.drop_column('parcels', 'document')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('document', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parcels_document_fkey', 'parcels', 'documents', ['document'], ['id'])
    op.add_column('documents', sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('documents_parcel_id_fkey', 'documents', 'parcels', ['parcel_id'], ['id'])
    # ### end Alembic commands ###
