"""parcel new fields

Revision ID: 58ab40a94f02
Revises: f2cb37d58bf3
Create Date: 2025-01-29 14:51:38.022917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ab40a94f02'
down_revision: Union[str, None] = 'f2cb37d58bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('kvartal', sa.String(), nullable=True))
    op.add_column('parcels', sa.Column('area_value', sa.Float(), nullable=True))
    op.add_column('parcels', sa.Column('date_cost', sa.DateTime(), nullable=True))
    op.add_column('parcels', sa.Column('permitted_use', sa.String(), nullable=True))
    op.add_column('parcels', sa.Column('readable_address', sa.String(), nullable=True))
    op.add_column('parcels', sa.Column('ownership_type', sa.String(), nullable=True))
    op.add_column('parcels', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'status')
    op.drop_column('parcels', 'ownership_type')
    op.drop_column('parcels', 'readable_address')
    op.drop_column('parcels', 'permitted_use')
    op.drop_column('parcels', 'date_cost')
    op.drop_column('parcels', 'area_value')
    op.drop_column('parcels', 'kvartal')
    # ### end Alembic commands ###
