"""fix_foreign_key_constraint

Revision ID: 5c97a9d62d9c
Revises: 310172ea6f5b
Create Date: 2025-02-01 23:38:28.638349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c97a9d62d9c'
down_revision: Union[str, None] = '310172ea6f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
