"""add document relation

Revision ID: 6062a4dce8cc
Revises: 6f247e45d774
Create Date: 2025-01-29 18:15:07.379231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6062a4dce8cc'
down_revision: Union[str, None] = '6f247e45d774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('document', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parcels', 'documents', ['document'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_column('parcels', 'document')
    # ### end Alembic commands ###
