"""add document relation

Revision ID: b062d2645c79
Revises: 385b77dc0cfb
Create Date: 2025-01-29 18:23:46.874598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b062d2645c79'
down_revision: Union[str, None] = '385b77dc0cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parcel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'parcels', ['parcel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'parcel_id')
    # ### end Alembic commands ###
