"""parcel new fields

Revision ID: cfc7a66dcfbb
Revises: 87462dce95fd
Create Date: 2025-01-31 00:04:35.937498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc7a66dcfbb'
down_revision: Union[str, None] = '87462dce95fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('code_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'code_id')
    # ### end Alembic commands ###
